Add /sbin:/usr/sbin to PATH to make sure iptables is found.

diff --git a/bin/chomper b/bin/chomper
--- a/bin/chomper
+++ b/bin/chomper
@@ -8,4 +8,11 @@ cd $PROJECTDIR && INTERPRETER=$(pipenv --py)
 cd $PROJECTDIR && MITMDUMP_BIN_PATH=$(pipenv --venv)/bin/mitmdump
 CURRENT_USER=$(whoami)
 
+PATH=${PATH}:/sbin:/usr/sbin
+if ! hash iptables 2>/dev/null; then
+   echo "ERROR: iptables not found in \$PATH\n"
+   echo "PATH=${PATH}"
+   exit 1
+fi
+
 sudo ${INTERPRETER} ${PROJECTDIR}/chomper/block.py --rule=$1 --block_length=$2 --settings_json_path=${PROJECTDIR}/data/block_settings.json --reset_command "env PATH=${PATH} ${INTERPRETER} ${PROJECTDIR}/chomper/reset.py" --mitmdump_bin_path=${MITMDUMP_BIN_PATH}
